const DATA = [
  {
    id: 1,
    cat: "wounds",
    icon: "\u{1FA79}",
    color: "#e5484d",
    colorDim: "rgba(229,72,77,0.15)",
    title: "Minor Cut or Wound",
    label: "Wounds & Bleeding",
    urgency: "low",
    preview: "Small cuts from sharp objects. Control bleeding and clean the wound to prevent infection.",
    warning: "Seek medical help if bleeding does not stop after 10 minutes, wound is deep or gaping, or caused by a rusty/dirty object.",
    steps: [],
    call: "Go to a clinic or ER if the wound is deep, wide, jagged, or will not stop bleeding after 10 minutes."
  },
  {
    id: 2,
    cat: "wounds",
    icon: "\u{1FA78}",
    color: "#e5484d",
    colorDim: "rgba(229,72,77,0.15)",
    title: "Severe Bleeding",
    label: "Wounds & Bleeding",
    urgency: "high",
    preview: "Heavy or uncontrolled bleeding from a large wound. Requires immediate action.",
    warning: "\u26A0\uFE0F Severe bleeding can be life-threatening. Call emergency services (911 or 8-911) immediately.",
    steps: [],
    call: "Call 911 or 8-911 immediately. Do not leave the person alone."
  },
  {
    id: 3,
    cat: "burns",
    icon: "\u{1F525}",
    color: "#f76b15",
    colorDim: "rgba(247,107,21,0.15)",
    title: "Minor Burn (1st Degree)",
    label: "Burns",
    urgency: "low",
    preview: "Superficial burn affecting only the outer skin. Caused by brief contact with heat or sun.",
    warning: "Do not use ice, butter, toothpaste, or any home remedies on burns. These make it worse.",
    steps: [],
    call: "See a doctor if the burn is larger than your palm, on the face/hands/feet, or shows signs of infection."
  },
  {
    id: 4,
    cat: "burns",
    icon: "\u{1F9EF}",
    color: "#f76b15",
    colorDim: "rgba(247,107,21,0.15)",
    title: "Severe Burn (2nd/3rd Degree)",
    label: "Burns",
    urgency: "high",
    preview: "Deep burns with blistering, raw tissue, or charred skin. Requires immediate medical care.",
    warning: "\u26A0\uFE0F Severe burns are a medical emergency. Do not remove clothing stuck to the burn.",
    steps: [],
    call: "This is an emergency. Call 911 or 8-911 immediately."
  },
  {
    id: 5,
    cat: "breathing",
    icon: "\u{1F62E}",
    color: "#3b82f6",
    colorDim: "rgba(59,130,246,0.15)",
    title: "Choking (Adult)",
    label: "Breathing",
    urgency: "high",
    preview: "Airway blockage causing inability to breathe, speak, or cough. A life-threatening emergency.",
    warning: "\u26A0\uFE0F If the person cannot speak, breathe, or cough, act now. Every second counts.",
    steps: [],
    call: "If the object cannot be dislodged, call 911 or 8-911 immediately."
  },
  {
    id: 6,
    cat: "breathing",
    icon: "\u{1F476}",
    color: "#3b82f6",
    colorDim: "rgba(59,130,246,0.15)",
    title: "Choking (Infant)",
    label: "Breathing",
    urgency: "high",
    preview: "Airway blockage in a baby under 1 year old. Requires a different technique than adults.",
    warning: "\u26A0\uFE0F Never perform abdominal thrusts on an infant. Use back blows and chest thrusts only.",
    steps: [],
    call: "Call 911 immediately if the baby becomes unconscious or you cannot clear the airway."
  },
  {
    id: 7,
    cat: "bone",
    icon: "\u{1FAB4}",
    color: "#30a46c",
    colorDim: "rgba(48,164,108,0.15)",
    title: "Suspected Fracture",
    label: "Bone & Muscle",
    urgency: "mid",
    preview: "A possible broken bone after a fall, impact, or accident. Immobilize and get medical help.",
    warning: "Do not try to straighten or reset the bone yourself. This can cause more damage.",
    steps: [],
    call: "Go to the ER or call 911 if the fracture is open (bone through skin), involves the spine, or the person is in severe shock."
  },
  {
    id: 8,
    cat: "bone",
    icon: "\u{1F300}",
    color: "#30a46c",
    colorDim: "rgba(48,164,108,0.15)",
    title: "Sprain or Strain",
    label: "Bone & Muscle",
    urgency: "low",
    preview: "Twisted ankle or stretched muscle. Use the RICE method to reduce pain and swelling.",
    warning: "If pain is severe, the area looks deformed, or you cannot move it at all, see a doctor. It may be fractured.",
    steps: [],
    call: "See a doctor if the pain is severe, swelling is extreme, or you cannot bear weight after 24 hours."
  },
  {
    id: 9,
    cat: "head",
    icon: "\u{1FA7A}",
    color: "#a855f7",
    colorDim: "rgba(168,85,247,0.15)",
    title: "Head Injury / Concussion",
    label: "Head",
    urgency: "high",
    preview: "A blow to the head that may cause dizziness, confusion, or loss of consciousness.",
    warning: "\u26A0\uFE0F Do not leave a person with a head injury alone for 24 hours. Symptoms can worsen suddenly.",
    steps: [],
    call: "Call 911 or go to ER immediately if they lose consciousness, vomit repeatedly, have a seizure, or cannot recognize people."
  },
  {
    id: 10,
    cat: "head",
    icon: "\u{1FA7B}",
    color: "#a855f7",
    colorDim: "rgba(168,85,247,0.15)",
    title: "Nosebleed",
    label: "Head",
    urgency: "low",
    preview: "Bleeding from the nose due to dry air, injury, or nose picking. Usually stops within minutes.",
    warning: "Do not tilt the head back. Blood may flow into the throat and cause choking or nausea.",
    steps: [],
    call: "See a doctor if the nosebleed lasts more than 20 minutes, follows a head injury, or involves large amounts of blood."
  },
  {
    id: 11,
    cat: "other",
    icon: "\u26A1",
    color: "#facc15",
    colorDim: "rgba(250,204,21,0.15)",
    title: "Electric Shock",
    label: "Other",
    urgency: "high",
    preview: "Injury caused by electrical current passing through the body. The source must be made safe first.",
    warning: "\u26A0\uFE0F Do not touch the person if they are still in contact with the electrical source. You could be electrocuted.",
    steps: [],
    call: "Always call 911 for electric shock. Internal injuries may not be visible."
  },
  {
    id: 12,
    cat: "other",
    icon: "\u{1F321}\uFE0F",
    color: "#facc15",
    colorDim: "rgba(250,204,21,0.15)",
    title: "Heat Stroke",
    label: "Other",
    urgency: "high",
    preview: "Dangerous overheating of the body. Skin is hot and dry, person may be confused or unconscious.",
    warning: "\u26A0\uFE0F Heat stroke is a medical emergency. The body's cooling system has failed. Act immediately.",
    steps: [],
    call: "Call 911 immediately. Heat stroke can cause organ damage or death if untreated."
  },
  {
    id: 13,
    cat: "other",
    icon: "\u{1F41D}",
    color: "#facc15",
    colorDim: "rgba(250,204,21,0.15)",
    title: "Insect Sting / Bite",
    label: "Other",
    urgency: "mid",
    preview: "Bee sting, wasp, or ant bite. Most are minor but watch for severe allergic reactions.",
    warning: "Watch for signs of severe allergy (anaphylaxis): throat swelling, difficulty breathing, dizziness. This is an emergency.",
    steps: [],
    call: "Call 911 if signs of anaphylaxis appear: difficulty breathing, throat tightening, dizziness, or rash spreading over the body."
  },
  {
    id: 14,
    cat: "wounds",
    icon: "\u{1FA77}",
    color: "#e5484d",
    colorDim: "rgba(229,72,77,0.15)",
    title: "Animal or Human Bite",
    label: "Wounds & Bleeding",
    urgency: "mid",
    preview: "Skin-breaking bites from animals or humans carry infection and disease risk.",
    warning: "All animal bites that break the skin need medical evaluation due to infection and rabies risk.",
    steps: [],
    call: "Go to a clinic or ER within hours. Rabies post-exposure treatment is time-sensitive."
  }
];


