const DATA = [
  {
    id: 1,
    cat: "wounds",
    icon: "\u{1FA79}",
    color: "#e5484d",
    colorDim: "rgba(229,72,77,0.15)",
    title: "Minor Cut or Wound",
    label: "Wounds & Bleeding",
    urgency: "low",
    preview: "Small cuts from sharp objects. Control bleeding and clean the wound to prevent infection.",
    warning: "Seek medical help if bleeding does not stop after 10 minutes, wound is deep or gaping, or caused by a rusty/dirty object.",
    steps: [
      "Wash your hands thoroughly with soap and water before touching the wound.",
      "Apply gentle pressure with a clean cloth or gauze for 5-10 minutes to stop bleeding.",
      "Once bleeding stops, rinse the wound under clean running water for 1-2 minutes.",
      "Gently clean around the wound with mild soap. Do not put soap directly inside the cut.",
      "Apply a thin layer of antibiotic ointment (e.g. Betadine) to prevent infection.",
      "Cover the wound with a sterile bandage or clean cloth. Change the bandage daily or when wet.",
      "Watch for signs of infection over the next few days: redness, swelling, warmth, or pus."
    ],
    call: "Go to a clinic or ER if the wound is deep, wide, jagged, or will not stop bleeding after 10 minutes."
  },
  {
    id: 2,
    cat: "wounds",
    icon: "\u{1FA78}",
    color: "#e5484d",
    colorDim: "rgba(229,72,77,0.15)",
    title: "Severe Bleeding",
    label: "Wounds & Bleeding",
    urgency: "high",
    preview: "Heavy or uncontrolled bleeding from a large wound. Requires immediate action.",
    warning: "\u26A0\uFE0F Severe bleeding can be life-threatening. Call emergency services (911 or 8-911) immediately.",
    steps: [
      "Call for emergency medical help (911 / 8-911) right away.",
      "Put on gloves or use a plastic bag to protect yourself from blood contact.",
      "Apply firm, direct pressure to the wound using a clean cloth, shirt, or gauze.",
      "Do not remove the cloth if it soaks through. Add more layers on top and keep pressing.",
      "If possible and trained, apply a tourniquet 2-3 inches above the wound for limb injuries.",
      "Keep the injured person lying down. Elevate legs slightly to reduce shock unless head or spine injury is suspected.",
      "Keep the person calm and warm. Stay with them until help arrives."
    ],
    call: "Call 911 or 8-911 immediately. Do not leave the person alone."
  },
  {
    id: 3,
    cat: "burns",
    icon: "\u{1F525}",
    color: "#f76b15",
    colorDim: "rgba(247,107,21,0.15)",
    title: "Minor Burn (1st Degree)",
    label: "Burns",
    urgency: "low",
    preview: "Superficial burn affecting only the outer skin. Caused by brief contact with heat or sun.",
    warning: "Do not use ice, butter, toothpaste, or any home remedies on burns. These make it worse.",
    steps: [
      "Remove the person from the source of heat immediately.",
      "Cool the burn under cool (not cold or ice) running water for at least 10-20 minutes.",
      "Remove jewelry or tight items near the burn area before swelling starts.",
      "Do not pop any blisters. They protect the skin beneath.",
      "Apply a sterile non-stick bandage or clean cloth loosely over the burn.",
      "You may take over-the-counter pain reliever like paracetamol (Biogesic) if needed.",
      "Keep the area clean and watch for signs of infection."
    ],
    call: "See a doctor if the burn is larger than your palm, on the face/hands/feet, or shows signs of infection."
  },
  {
    id: 4,
    cat: "burns",
    icon: "\u{1F9EF}",
    color: "#f76b15",
    colorDim: "rgba(247,107,21,0.15)",
    title: "Severe Burn (2nd/3rd Degree)",
    label: "Burns",
    urgency: "high",
    preview: "Deep burns with blistering, raw tissue, or charred skin. Requires immediate medical care.",
    warning: "\u26A0\uFE0F Severe burns are a medical emergency. Do not remove clothing stuck to the burn.",
    steps: [
      "Call emergency services (911 / 8-911) immediately.",
      "Move the person away from the fire or heat source. Make sure you are safe too.",
      "Do not pour water on large or severe burns. This can cause shock.",
      "Do not remove clothing stuck to the burned skin.",
      "Cover the burn loosely with a clean, dry non-fluffy material (cling wrap is ideal).",
      "Do not apply creams, butter, ice, or any substances to the burn.",
      "Keep the person warm and monitor their breathing until help arrives."
    ],
    call: "This is an emergency. Call 911 or 8-911 immediately."
  },
  {
    id: 5,
    cat: "breathing",
    icon: "\u{1F62E}",
    color: "#3b82f6",
    colorDim: "rgba(59,130,246,0.15)",
    title: "Choking (Adult)",
    label: "Breathing",
    urgency: "high",
    preview: "Airway blockage causing inability to breathe, speak, or cough. A life-threatening emergency.",
    warning: "\u26A0\uFE0F If the person cannot speak, breathe, or cough, act now. Every second counts.",
    steps: [
      "Ask: \"Are you choking?\" If they cannot speak or breathe, act immediately.",
      "Tell the person you are going to help them.",
      "Lean them slightly forward and give up to 5 firm back blows between the shoulder blades with the heel of your hand.",
      "If back blows do not work, perform abdominal thrusts (Heimlich maneuver): stand behind them, arms around the waist.",
      "Make a fist just above the navel. Grab your fist with your other hand. Give 5 quick upward-inward thrusts.",
      "Alternate 5 back blows and 5 abdominal thrusts until the object is expelled or help arrives.",
      "If the person becomes unconscious, carefully lower them to the ground and begin CPR if trained. Call 911."
    ],
    call: "If the object cannot be dislodged, call 911 or 8-911 immediately."
  },
  {
    id: 6,
    cat: "breathing",
    icon: "\u{1F476}",
    color: "#3b82f6",
    colorDim: "rgba(59,130,246,0.15)",
    title: "Choking (Infant)",
    label: "Breathing",
    urgency: "high",
    preview: "Airway blockage in a baby under 1 year old. Requires a different technique than adults.",
    warning: "\u26A0\uFE0F Never perform abdominal thrusts on an infant. Use back blows and chest thrusts only.",
    steps: [
      "Call for someone to get help or call 911 while you help the baby.",
      "Hold the baby face-down on your forearm, supporting their head. Keep the head lower than the chest.",
      "Give 5 firm back blows between the shoulder blades using the heel of your hand.",
      "Turn the baby face-up. Use 2 fingers to give 5 chest thrusts in the center of the chest, just below the nipple line.",
      "Alternate 5 back blows and 5 chest thrusts.",
      "Check the mouth after each cycle. Remove the object only if you can clearly see it.",
      "If the baby stops breathing, begin infant CPR and call 911 immediately."
    ],
    call: "Call 911 immediately if the baby becomes unconscious or you cannot clear the airway."
  },
  {
    id: 7,
    cat: "bone",
    icon: "\u{1FAB4}",
    color: "#30a46c",
    colorDim: "rgba(48,164,108,0.15)",
    title: "Suspected Fracture",
    label: "Bone & Muscle",
    urgency: "mid",
    preview: "A possible broken bone after a fall, impact, or accident. Immobilize and get medical help.",
    warning: "Do not try to straighten or reset the bone yourself. This can cause more damage.",
    steps: [
      "Keep the injured person as still as possible. Do not move them unless in immediate danger.",
      "Immobilize the injured area. Do not try to align the bone.",
      "Apply a splint if available: use a stiff item (ruler, board) padded with cloth. Secure above and below the break.",
      "Apply an ice pack wrapped in cloth (not directly on skin) to reduce swelling for 20 minutes at a time.",
      "Elevate the injured limb if possible unless it causes pain.",
      "Watch for signs of shock: pale skin, rapid breathing, weakness. Lay the person down, elevate feet slightly.",
      "Get the person to an emergency room as soon as possible."
    ],
    call: "Go to the ER or call 911 if the fracture is open (bone through skin), involves the spine, or the person is in severe shock."
  },
  {
    id: 8,
    cat: "bone",
    icon: "\u{1F300}",
    color: "#30a46c",
    colorDim: "rgba(48,164,108,0.15)",
    title: "Sprain or Strain",
    label: "Bone & Muscle",
    urgency: "low",
    preview: "Twisted ankle or stretched muscle. Use the RICE method to reduce pain and swelling.",
    warning: "If pain is severe, the area looks deformed, or you cannot move it at all, see a doctor. It may be fractured.",
    steps: [
      "R - Rest: Stop the activity and avoid putting weight on the injured area.",
      "I - Ice: Apply an ice pack wrapped in a cloth for 15-20 minutes every 2-3 hours for the first 48 hours.",
      "C - Compression: Wrap the area with an elastic bandage. Not too tight. Loosen if it causes numbness or swelling below.",
      "E - Elevation: Raise the injured limb above heart level when resting to reduce swelling.",
      "Take over-the-counter pain relief like ibuprofen or paracetamol if needed.",
      "Avoid heat, massage, or alcohol for the first 72 hours. These increase swelling.",
      "Gradually return to light activity after 2-3 days if pain allows."
    ],
    call: "See a doctor if the pain is severe, swelling is extreme, or you cannot bear weight after 24 hours."
  },
  {
    id: 9,
    cat: "head",
    icon: "\u{1FA7A}",
    color: "#a855f7",
    colorDim: "rgba(168,85,247,0.15)",
    title: "Head Injury / Concussion",
    label: "Head",
    urgency: "high",
    preview: "A blow to the head that may cause dizziness, confusion, or loss of consciousness.",
    warning: "\u26A0\uFE0F Do not leave a person with a head injury alone for 24 hours. Symptoms can worsen suddenly.",
    steps: [
      "Check if the person is conscious and responsive. If unconscious, call 911 immediately.",
      "Keep the person still. Do not move them if a spinal injury is possible.",
      "Apply a clean cloth gently to any bleeding scalp wound. Do not apply pressure if skull fracture is suspected.",
      "Monitor for warning signs: loss of consciousness, vomiting more than once, confusion, seizures, unequal pupils.",
      "Do not give pain relievers like aspirin or ibuprofen. These can increase bleeding.",
      "Allow the person to rest. Do not let them \"sleep it off\" without checking on them every 30 minutes.",
      "Keep them awake if they seem drowsy and drive them to an ER or call for help."
    ],
    call: "Call 911 or go to ER immediately if they lose consciousness, vomit repeatedly, have a seizure, or cannot recognize people."
  },
  {
    id: 10,
    cat: "head",
    icon: "\u{1FA7B}",
    color: "#a855f7",
    colorDim: "rgba(168,85,247,0.15)",
    title: "Nosebleed",
    label: "Head",
    urgency: "low",
    preview: "Bleeding from the nose due to dry air, injury, or nose picking. Usually stops within minutes.",
    warning: "Do not tilt the head back. Blood may flow into the throat and cause choking or nausea.",
    steps: [
      "Sit upright and lean slightly forward (not backward).",
      "Pinch the soft part of your nose (just below the bony bridge) firmly.",
      "Breathe through your mouth and hold for 10-15 minutes without releasing.",
      "Apply a cold compress or ice pack (wrapped in cloth) to the bridge of the nose.",
      "Do not stuff tissues deep inside the nostril.",
      "After bleeding stops, avoid blowing your nose or bending over for several hours.",
      "Avoid strenuous activity, hot drinks, or anything that raises blood pressure for the rest of the day."
    ],
    call: "See a doctor if the nosebleed lasts more than 20 minutes, follows a head injury, or involves large amounts of blood."
  },
  {
    id: 11,
    cat: "other",
    icon: "\u26A1",
    color: "#facc15",
    colorDim: "rgba(250,204,21,0.15)",
    title: "Electric Shock",
    label: "Other",
    urgency: "high",
    preview: "Injury caused by electrical current passing through the body. The source must be made safe first.",
    warning: "\u26A0\uFE0F Do not touch the person if they are still in contact with the electrical source. You could be electrocuted.",
    steps: [
      "Do not touch the person until the electrical source is off.",
      "Turn off the power at the switch or circuit breaker if possible.",
      "If you cannot switch off, use a dry non-conductive object (wooden broom, rubber mat) to push the source away.",
      "Once safe, check if the person is breathing. Call 911 immediately.",
      "If they are not breathing and you are trained, begin CPR.",
      "If they are conscious, lay them down and keep them warm and still.",
      "Check for burns at the entry and exit points of the current and treat as a burn wound."
    ],
    call: "Always call 911 for electric shock. Internal injuries may not be visible."
  },
  {
    id: 12,
    cat: "other",
    icon: "\u{1F321}\uFE0F",
    color: "#facc15",
    colorDim: "rgba(250,204,21,0.15)",
    title: "Heat Stroke",
    label: "Other",
    urgency: "high",
    preview: "Dangerous overheating of the body. Skin is hot and dry, person may be confused or unconscious.",
    warning: "\u26A0\uFE0F Heat stroke is a medical emergency. The body's cooling system has failed. Act immediately.",
    steps: [
      "Call 911 or get the person to a hospital immediately.",
      "Move the person to a cool, shaded, or air-conditioned area right away.",
      "Remove excess clothing.",
      "Cool them rapidly: apply cool (not ice cold) water to skin, fan them, place ice packs on neck, armpits, and groin.",
      "If conscious and not vomiting, give small sips of cool water.",
      "Do not give aspirin or ibuprofen. They can worsen the condition.",
      "Monitor breathing and consciousness until help arrives."
    ],
    call: "Call 911 immediately. Heat stroke can cause organ damage or death if untreated."
  },
  {
    id: 13,
    cat: "other",
    icon: "\u{1F41D}",
    color: "#facc15",
    colorDim: "rgba(250,204,21,0.15)",
    title: "Insect Sting / Bite",
    label: "Other",
    urgency: "mid",
    preview: "Bee sting, wasp, or ant bite. Most are minor but watch for severe allergic reactions.",
    warning: "Watch for signs of severe allergy (anaphylaxis): throat swelling, difficulty breathing, dizziness. This is an emergency.",
    steps: [
      "Move away from the area to avoid more stings.",
      "If a stinger is visible (bee sting), scrape it out sideways with a flat object like a credit card. Do not squeeze it.",
      "Wash the area with soap and water.",
      "Apply a cold pack wrapped in cloth to reduce pain and swelling for 10-15 minutes.",
      "Take an antihistamine (e.g. Cetirizine/Zyrtec) for itching and mild swelling.",
      "Apply calamine lotion or hydrocortisone cream if available.",
      "Keep the area elevated if possible. Avoid scratching to prevent infection."
    ],
    call: "Call 911 if signs of anaphylaxis appear: difficulty breathing, throat tightening, dizziness, or rash spreading over the body."
  },
  {
    id: 14,
    cat: "wounds",
    icon: "\u{1FA77}",
    color: "#e5484d",
    colorDim: "rgba(229,72,77,0.15)",
    title: "Animal or Human Bite",
    label: "Wounds & Bleeding",
    urgency: "mid",
    preview: "Skin-breaking bites from animals or humans carry infection and disease risk.",
    warning: "All animal bites that break the skin need medical evaluation due to infection and rabies risk.",
    steps: [
      "If bleeding, apply pressure with a clean cloth to stop it.",
      "Wash the wound thoroughly with soap and water for at least 5 minutes.",
      "Rinse with clean running water to flush out bacteria.",
      "Apply an antiseptic (e.g. Betadine/Povidone-iodine) to the wound.",
      "Cover loosely with a sterile bandage.",
      "Note the animal: type, vaccination status if known, and whether it was provoked.",
      "Seek medical care immediately for proper wound care and to assess need for rabies vaccine."
    ],
    call: "Go to a clinic or ER within hours. Rabies post-exposure treatment is time-sensitive."
  }
];
